### ISSUE TITLE
Vytvorenie katalógu požiadaviek

### ISSUE THREAD

**Issue by krivanek06** [TIS2019-FMFI/ims-spectrometer#1]
Treba vytvoriť katalóg požiadaviek do 16.10 a poslať Petrovičovi na schválenie

**Comment by pavelpetrovic** [comment]
Dakujem za vypracovanie KP. Na prvy raz je to celkom dobre, ale este mame pred sebou vela prace. Tu su moje strucne pripomienky, prosim, zapracujte ich a poslite mi novu verziu, PRED TYM, ako to budete konzultovat so zadavatelom. Az ked budeme my dohodnuti na vysledku, POTOM posielajte CELY KP zadavatelovi - ak ako sme sa uz dohodli.

- kazdy formalny dokument by mal mat v poriadku gramatiku, napr. ", ktorí vynikol " alebo "ktorý potrebujú"
- katedru fyziky => ta katedra ma iny presny nazov, kazde slovo v tomto dokumente musi byt presne a spravne!!
- (arduin) => myslite Arduino?
- K 3. kapitole:
vsetky poziadavky treba formulovat ako nejaka hodnota, ktoru pouzivatelovi aplikacia prinasa. To znamena, vo forme celych viet, napr. 
"3.1.1.	Spustenie aplikácie - tlačidlo, kde uživateľ má možnosť zastaviť a znovu pustiť meranie dát z arduina"
treba zapisat takto (poziadavky treba rozdelit na atomicke):
"3.1.1. Používateľ môže odštartovať meranie dát pomocou samostatného tlačidla, ktoré je dostupné ?v hlavnom okne? aplikácie.
3.1.2. Používateľ môže ?pomocou toho istého? tlačidla pozastaviť meranie dát.
3.1.3. Pozastavené meranie môže používateľ znovu spustiť ?stlačením toho istého tlačidla?"

(lepšie by bolo to tlačidlo aj nejak pomenovať a osobne by sa mi viac páčilo, keby tam boli 
tri tlačidlá v štýle "Start", "Stop", "Pause", aby to bolo jednoznačné a zrozumiteľné)

Takýmto spôsobom treba spracovať všetky požiadavky.

3.1.2. táto požiadavka je nezrozumiteľná. Rozumiete jej možno Vy a zadávateľ, ale v dokumente by to malo byť vysvetlené tak, aby nič podstatné neostalo nevypovedané. Vôbec nie je jasné, čo sú "agregované údaje z Arduina" - nie je to vysvetlené ani v slovníku pojmov ani nikde inde v dokumente.

3.1.3. opät - vôbec nie je z dokumentu jasné, ako bude tento Auto Save fungovať, treba to napísať presne. Možno stačia aj tri slová, ak sú výstižné, ale z toho, čo je tam teraz, to určite nie je jasné. Pripomínam ešte raz, že text má byť gramticky správny.

3.1.5. opäť nedefinované pojmy

3.1.6. nejasné

3.1.7. kam to bude vypisovať?

3.1.8. čo je daný repeat?

3.1.9. treba vysvetliť aj uviesť vzorec

3.1.10. si vyžaduje nákres (obrázok) - možno ste dostali nejaké podklady, môžete tam priložiť priamo z nich a lepšie vysvetliť

3.1.11. prečo je CSV súborov viac? čo sú to zač?

3.1.12. určite GRB? nemá byť RGB? ako presne má byť možné farby meniť?

3.1.13. čo je to "vedla"?

3.1.14. ako?

3.1.16. tyka sa to tych istych akcii ako 3.1.15? ak ano, uvedte to

3.1.17. 20000ms je defaultna hodnota, alebo sa to menit neda? ak sa to menit neda, nemalo by to byt pod 3.1.17, ktore hovori, ze sa to menit da. (konflikt, nejednoznacnost)

chyba mi:
 - nejaka informacia o tom, ci su obmedzenia na to, aky typ aplikacie to ma byt. z 3.3. mam skoro dojem, ze to moze byt webova aplikacia, ale mozno ste to tak nemysleli. ak by to tak ale bolo, tak by nemala byt uplne volne dostupna na internete bez prihlasenia, ak sa tym da nieco naozaj startovat.

- chyba mi informacia o tom, ci sa rozhranie bude vediet prisposobit rozliseniu monitora, alebo nie. ak to niekto pusti na monitore 5000x4000 bodov, bude tam mat mrnave okienko v ktorom nic neuvidi? ak to niekto pusti na rozliseni 800x600 stane sa mu, ze mu okno ani nevojde na obrazovku a nebude vediet stlacit niektore tlacidla, lebo budu za hranicou obrazovky?

chyba mi informacia o tom, ze Arduino (ak si dobre pamatam) uz je naprogramovane a teda ho nemusite riesit, resp. tusim ste vraveli nieco o tom, ze aj na komunikaciu s Arduinom je uz nejaka kniznica? ci? v kazdom pripade aj toto - ak zadavatel povedal je jeho poziadavka (nevztahujuca sa na funkcionalitu, ale na sposob prevedenia), cize to treba v dokumente uviest.

vysvetlite to vsetko v dokumente poriadne, tak aby sa to z neho dalo pochopit bez osobnej komunikacie a poslite mi novu verziu. rozdelte si ulohy, aby to nerobil jeden clovek.

zamyslite sa, ci okrem toho, co Vam povedali, budete potrebovat este nejake dalsie informacie, ktore nemate. urcite take su, najdite ich, zistite odpovede a zahrnte to ako poziadavky do dokumentu.
