### ISSUE TITLE
Katalóg požiadaviek - klient

### ISSUE THREAD

**Issue by krivanek06** [TIS2019-FMFI/ims-spectrometer#2]
Poslať schválený katalóg požiadaviek klientovi.

**Comment by pavelpetrovic** [comment]
neviem kde mam hladat aktualny KP. 
dakujem aj za zapisnice, mozete ich, prosim, pisat na wiki ako ostatne skupiny?
(tieto dve tam mozete nahrat tiez).
je to tam ovela jednoduchsie pozeratelne, ako ked musim subory downloadovat a otvarat vo worde.
p.

**Comment by pavelpetrovic** [comment]
dakujem, nasiel som KP.
tu su moje strucne komentare:
 - do nadpisu prosim pridajte nazov projektu a svoje mena
 - prosim dajte pozor, aby ste nerobili hrubky, napr. "ktorí vznikol", "každý bodka", "nameranej hodnotu", "ktorý potrebujú", "či je meria dát", "na Y-novej osy" (bzzz) a este kopec dalsich...
 - študentov a profesorov => studentov a zamestnancov 
 - fakulte fyziky  => Katedre experimentálnej fyziky
 - k jednotlivým požiadavkám:

VŠETKY POŽIADAVKY MAJÚ BYŤ PÍSANÉ AKO HODNOTA, KTORÚ APLIKÁCIA POUŽÍVATEĽOVI POSKYTUJE

t.j. napr. namiesto

"Tlačidlo Start - tlačidlo, kde užívateľ má možnosť zastaviť a znovu pustiť meranie dát z arduino na hlavnom okne."

treba uviesť:

"Používateľ môže zastaviť a znovu spustiť meranie dát z Arduina pomocou tlačidla Štart umiestneného v hlavnom okne". 

je to detail, ale pre mna podstatny, prosim vsetky poziadavky preformulujte v tomto duchu. mnohe z nich uz vyhovuju tejto predstave, ale nie vsetky. naviac, z tychto poziadaviek by sa to malo dat naprogramovat. toto zatial nie je pravda, niektore ostali zamlcane. 

aktualna verzia KP ma potesila a ide velmi dobrym smerom, ale este predsa len zostava kus roboty, aby to bolo pekne.

ďalej viac vecne:

3.1.1  - 3.1.3 prosim preformulovat, aby si citatel nepripadal ako blbec: najskor sa docita, ze start zastavuje, potom sa docita, ze nielen start zastavuje, ale aj stop zastavuje a potom mu vysvetlite, ze vlastne ten start je to iste ako stop. to sa naozaj neda napisat normalne?

3.1.4. dokument do tohto miesta ani na tomto mieste nevysvetluje, co su agregovane udaje, resp. agregovane udaje s aplikovanim mobility. tento dokument by mal byt kompletny, clovek by sa v nom mal docitat vsetko, nic podstatne nema zostat nevypovedane (iba vo Vasich hlavach). Tieto pojmy aj tie vzorce pre mobilitu, ktore uvadzate potom dalej by bolo asi najlepsie vysvetlit v 2. casti KP a potom sa na jasne definovane pojmy v casti 3 staci odkazat. dakujem.

3.1.5. "pri zapnutí tejto funkcionality" => ako sa tato funkcionalita bude zapinat?
"miesto v balíku aplikácie" => co to je?
"odkiaľ s ich užívateľ vie zobrať" => ako? co tym myslite?

3.1.6. => tym myslite to, co je v 3.1.19 alebo aj nieco ine? prosim upresnite to v tejto poziadavke (aspon krizovym odkazom na 3.1.19 alebo najlepsie presne uvedte co)

3.1.7. => "pod každým grafom" => tam bude tych grafov viac? mohli by ste nejakou poziadavkou upresnit, co vsetko bude naraz zobrazene a ako priblizne? aha, nieco vidim v 3.1.8, ale to mi pride neskoro, ked az po 3.1.7. v dokumente nic nie je a ani krizova referencia ma nikam nenasmeruje. aj tak nerozumiem ako sa vojde 100 grafov a pod nimi 100 tlacidiel "Save" - to sa bude dat v tom nejak scrollovat?

ak existuje nejaky ilustracny obrazok ako tie grafy maju vyzerat, velmi by to pomohlo zrozumitelnosti textu, ak nie je, tak, prosim, nejaky spravte - keby aj ceruzkou na papier a odfotit, stale lepsie ako nic.

celkovo su tieto poziadavky 3.1.7, 3.1.8 napisane gramaticky nezrozumitelne. pokial vo Vasej skupine nikto nevie po slovensky, tak mozete dokument napisat aj po anglicky.

3.1.9 => iba poslednú hodnotu, alebo tam bude appendovať?

3.1.10 => iba ked mys zastane, alebo stale? nebolo by lepsie, keby sa tie hodnoty zobrazovali niekde pod alebo vedla grafu na tom istom mieste ako sa hybe kurzor mysi? bolo by mozne zmenit kurzor mysi - ked je mys nad grafom na tenky krizik, aby bolo jasne, na ktory bod sa ukazuje?

3.1.11 => kde sa budu tieto parametre nastavovat?

3.1.12. => toto je necitatelne, prosim, po slovensky a zrozumitelne. napr. "graf sa meria"?? "body ako usecka"?? co je "realny cas"? tu "premennu" pouzivatel nastavuje ako?

3.1.13 => prosim tiez lepsie rozpisat. ako si natiahne subory? su to vsetky subory z jedneho priecinka, alebo nejak podobne pomenovane? alebo ako ich oznaci, ktore sa maju nacitat? odkial sa vzali?  je ich format uz znamy? ak ano, odkazte sa na nejaky priklad v odkazoch, alebo na specifikaciu formatu...

3.1.14 => co to znamena, ze spadaju do toho isteho rozsahu? co je to dany rozsah? kolko ich je? urcuju sa automaticky, alebo su nejak pevne zadane, alebo ich musi nakonfigurovat? nerozumiem.

3.1.15 => toto plati aj pocas merania, alebo iba az ked sa domeralo?

3.1.16 => os sa nezvacsuje/nezmensuje, ale jej rozsah. tyka sa to len maximalnej hranice alebo aj minimalnej hranice? ak by sa dala zmenit aj minimalna hranica (a neostavala vzdy 0), graf by sa mohol zafokusovat na prislusnu oblast (a teda v principa aj posuvat).  nedalo by sa to dosiahnut aj nejakymi mysacimi gestami (tahanie vlavo-vpravo, hore-dole a scrollovacie koliesko) ked je mys nad grafom? bolo by to ovela viac user-friendly a nie az tak narocne na naprogramovanie.

3.1.19.6 dajte prec, ak mate 3.1.20

3.4. "Týmto sme dostali voľných 60 000 mikrosekúnd, kde sa nedeje nič." nerozumiem. A odstavcu podtym vobec nie. Neodkazujte sa na zadavatela, ten je v celkom dokumente implicitny. Napiste, co aplikacia bude/ma robit.

este mam otazocku:
- ako sw bude reagovat na odpojenie/vypnutie resp. pripojenie/zapnutie spektrometra?

**Comment by pavelpetrovic** [comment]
- 3.1.1 az 3.1.4.
Meranie sa spusta, resp. zastavuje tym istym tlacidlom Start, resp. Stop, ktore meni label podla stavu merania.

3.1.5 prosim pridat krizovu referenciu na 3.1.9

slovnik pojmov pri vysvetleni agregovanych dat hovori o sekunde, ale v 3.1.6. ste mi povedali, ze to nemusi byt sekunda. prosim, upresnit vyznam v slovniku pojmov

zistit: "aplikovanim mobility" ??

3.1.6. nie je explicitne jasne, ze pri kazdom jednom merani sa spravi novy subor.
vysvetlit, checkbox, nie tlacidlo

3.1.7. nastavení aplikácie => nastavenie spektrometra, pozri. 3.1.25.

3.1.8. ak su uz agregovane, tak sa uz nepriemeruju, pocet priemerov vobec nespominat, vyplyva to z nastaveni rezimu agregovania
pridat na zaciatok? "Počas merania"

3.1.9.	Mobility – Mobilita je parametrizovateľná funkcia, ktorá sa popri aktuálnych agregovaných dátach môže zobrazovať v grafe. Je to funkcia času. Jej účel je znázornenie redukovanej pohyblivosti iónov, kvôli lepšej identifikácii iónov. Je nepriamo úmerná času. Teda ióny s vysokou mobilitou dopadnú na detektor za kratší čas, a opačne tie pomalšie ióny budú mať nižšiu mobilitu. Mobilita má parametre:

3.1.10. agregovany graf = hlavny (pouzivat konzistentnu terminologiu)

POTREBUJEM obrazky kazdeho grafu (s popisanymi osami)
aj s popisom prosim


3.1.11.1.	(dĺžku trubice-L(cm) 
3.1.11.2.	tlak plynu - p- (pa)
3.1.11.3.	teplotu plynu T(K)
3.1.11.4.	napätie na driftovej trubici U (kV))
3.1.11.5.	normálny tlak po = 101325 Pa 
3.1.11.6.   To ....

Mobilitu nakoniec vyrátame vzorcom: Ko=(L^2/U*t)[(p*To)/(po*T)).


Navrhujem 3.1.18. presunut na zaciatok s tym, ze text oznami, co je na obrazku.
(strucne - vymenuje)

3.1.19. celkom sa stracam

3.1.20. som v tom istom bludisku

3.1.21. Pre hlavny graf na zaciatok, aby bolo jasne, ze sa vsetko tyka jeho
upresnit, ze ide len o 1 hodnotu - maximum

3.1.22. nie je minimalny a maximalny rozsah ale rozsah od min do max
pochopil som to ako zoom-in, nevidim zoom-out

3.2 sa moze zrusit

2.3 a 3.3. zjednotit do 2.3  a v 3.3. staci:
Systém bude desktopová aplikácia. Veľkosť okna pre aplikáciu bude v rozmedzí 1280 × 720.


3.1.25.0. režim merania: výber z možností: {time, count}

3.1.26 nie natvrdo, ale predvolena
3.1.26.	Dĺžka merania – hodnota v mikrosekundách určujúca periódu merania spektrometra, hodnota je v rozsahu 0-20 000 usec, predvolená hodnota 20 000.

**Comment by krivanek06** [comment]
Zdravím, nahrali sme opravený katalóg požiadaniek.
https://github.com/TIS2019-FMFI/ims-spectrometer/blob/master/Documents/Katalog_po%C5%BEiadaviek.pdf

**Comment by pavelpetrovic** [comment]
Dakujem pekne za rychlu aktualizaciu, tu su este moje posledne navrhy:

* 1.3. "3D reprezentacia" -> "3D reprezentácia (2D+farba)"
"priemer údajov z cyklov merania za dobu definovanou užívateľom" 
=> "vektor obsahujúci spriemerované údaje z cyklov merania po zložkách za dobu definovanú používateľom"

* v casti 2 mi chyba zmienka o tom, ze "Každý riadok v Intenzitnom grafe zodpovedá jednému zobrazeniu v Hlavnom grafe. Kliknutím na niektorý riadok Intenzitného grafu sa dá spätne zrekonštruovať zodpovedajúci priebeh v takom tvare, ako bol zobrazený v Hlavnom grafe, v aplikácii sa označuje ako Zrkadlový graf".   

* 3.1.3 "ktoré bežia vo vlastnom vlákne." - je implementacna technikalita, ktora by sa v KP nemala objavovat, zadavatel tomu pravdepodobne nebude rozumiet. Navrhujem bud odstranit, alebo nahradit niecim ako "Počas merania a automatickej aktualizácie Hlavného grafu má používateľ stále dostupné všetky riadiace prvky používateľského rozhrania" - ale potom by som to asi oddelil do samostatnej požiadavky.

* 3.1.4. vysla nam z toho asi menej gramaticky spravna veta, co tak napriklad:
"Používateľ bude mať možnosť vybrať si z dvoch spôsobov agregovania údajov. Perióda agregovania bude definovaná buď 1) časovým úsekom, alebo 2) počtom cyklov merania. (bod 3.1.22)."

* 3.1.5 mam este jeden navrh, myslim, ze sme o tom uz trochu hovorili. v hlavnom GUI by mohol byt jeden editbox, do ktoreho by pouzivatel napisal nazov projektu (resp. pri nacitani zo suboru by sa vyplnil automaticky). vsetky subory, ktore aplikacia vytvara, by mali tento nazov projektu ako prefix. preto by mohli mat ulozene nastavenia pre rozne projekty a vratit sa k nim (bez toho, aby hadali, ktory timestamp tomu zodpoveda) a nastavenia by sa im neprepisovali a rovnako by sa lahko nasli datove subory a nemiesali by sa im medzi roznymi projektami. ak suhlasite, tak tam, prosim pridajte este takuto poziadavku. napr. 
"3.1.25 Hlavné okno používateľského rozhrania obsahuje editovací riadok, do ktorého používateľ vpíše meno svojho projektu (reťazec písmen/číslic bez medzier). Toto meno sa pridáva pred názvy všetkých súborov, ktoré aplikácia vytvára a automaticky dopĺňa po načítaní vopred uloženého súboru." a potom pridajte ešte "<meno projektu>_" do požiadaviek 3.1.5., 3.1.6. a 3.1.18.2. Samozrejme lepšie zaradiť niekde skôr ako 3.1.25, ak nie je náročné prečíslovať požiadavky.

* 3.1.8. toto treba určite upraviť podľa toho, čo sme sa dozvedeli na stretnutí, napr.

"Mobilita je parametrizovateľná funkcia, ktorá slúži na zobrazenie údajov vo všetkých troch typoch grafov v transformovaných súradniciach. Vstupom do funkcie je pôvodná x-ová hodnota (čas t) a výstupom je nová x-ová hodnota (čas), pre zobrazenie príslušného bodu krivky grafu. Jej účel je znázornenie redukovanej pohyblivosti iónov, kvôli lepšej identifikácii iónov. Je nepriamo úmerná času. Teda ióny s vysokou mobilitou dopadnú na detektor za kratší čas, a opačne tie pomalšie ióny budú mať nižšiu mobilitu. Mobilita má parametre:
o dĺžku trubice - L(cm)
o tlak plynu - p (pa)
o teplotu plynu - T(K)
o napätie na driftovej trubici - U (kV))
o normálny tlak 101325 Pa - po
o 293.15 Kelvinov - To
Mobilitu nakoniec vyrátame vzorcom: Ko=(L^2/U*t)[(p*To)/(po*T)).
Checkbox „aplikovať“ v kolónke pre mobilitu bude rozhodovať či sa má mobilita aplikovať, alebo nie."

A ešte by som pridal: "Mobilita sa aplikuje na všetky zobrazené grafy."

* tiez na zaklade stretnutia:  poziadavky 3.1.9 a 3.1.10 nahradit napr. tymto:

"3.1.9 Používateľ môže vyznačením pravouhlého rámčeka pomocou myši určiť ľubovoľný menši výsek grafu, ktorý sa má priblížiť (zoom in) a zobraziť na celej ploche grafu. Vedľa počiatku osí je malé tlačidlo, ktoré priblíženie vráti a spôsobí zobrazenie grafu v celom pôvodnom rozsahu (zoom out)."

* 3.1.11. "počet agregovaných dát" => "poradie (počítadlo) agregovaných dát"

* 3.1.15 pridal by som: "Pokiaľ ešte používateľ na žiaden riadok intenzitného grafu neklikol, v zrkadlovom grafe sa nič nezobrazuje."

* 3.1.16. - 3.1.17. na zaklade toho, co sme videli na stretnuti, navrhujem prehodnotit/zvazit tieto dve poziadavky. Ten intenzitny graf, aby sa im dobre pozeral, je skoro na celu obrazovku... mne by sa najviac pacilo, aby kazdy, ktory si otvoria bol v samostatnom okne, pricom okno by bolo skalovatelne. takto by vedeli dosiahnut, ze sa divaju aj na viacero z nich naraz, ked si tie okna prisposobia ako potrebuju. zaroven by ste sa nemuseli paprat so skrolovanim celeho panelu, schovavanim grafov (to by bolo len zatvorenie okna). co Vy na to? (bolo by to vrátane toho intenzitného grafu, ktorý sa generuje z hlavného grafu - tiež by bol v samostatnom okne, potom aj ten hlavný graf by mohol byť väčší, ako majú oni v tej aplikácii)

* 3.1.18.3. pridal by som: "Stlačením Start sa predchádzajúci zobrazený graf (hlavný a hlavný intenzitný) zmaže."

* 3.1.21. prosím upresniť rozsahy a presnosť (počet desatinných miest, ak je to relevantné) pre každé jedno nastavenie. Prosím pridať: "Zmena nastavení spôsobí zmazanie hlavného a hlavného intenzitného grafu".

* 3.1.24. nerozumiem vzťahu medzi termínmi  "cyklus merania" a  "dĺžka merania"
A) je to to isté (potom prosím použiť iba jeden z nich)
B) cyklus merania je maximálna hranica pre dĺžku merania, ktorú nesmie prekročiť, ak ju prekročí, tak sa niekde vypíše správa
C) niečo iné.
Vo všetkých troch prípadoch prosím upresniť.

Ešte potrebujem jednu predposlednú vec: hoci na základe intenzívnej komunikácie už rozumiem o čo ide, z tohto dokumentu by to po nás stále asi nikto nedokázal pochopiť. Navrhujem doplniť niečo takéto do druhej časti:

"Priebeh fyzikálneho merania je približne nasledovný: v meracom prístroji na jednom mieste po vytvorení pulzu vznikajú ióny, ktoré následne letia trubicou, v ktorej je elektrické pole a to ich usmerňuje, aby doleteli až po detektor. Podľa vlastností iónu prelet trvá rôznu dobu a preto rozličné ióny detektor zachytí v rozličnom čase. Približne po 20 ms sa už dopad ďalších iónov neočakáva a cyklus merania sa ukončuje. Počas cyklu merania sa (s nastaviteľnou frekvenciou) neustále sníma intenzita vybudenia detektora. Takéto cykly merania sa opakujú jeden za druhým. Časovo zodpovedajúce okamihy v jednotlivých cykloch merania sa krížom cez niekoľko za sebou nasledujúcich cyklov merania priemerujú. Až takýto vektor spriemerovaných hodnôt sa zobrazuje v Hlavnom grafe."

a posledná vec do časti 2:

"Okrem súborov s uloženými nastaveniami aplikácia vytvára dva typy dátových CSV súborov. Prvý zodpovedá jednému zobrazeniu v Hlavnom grafe, obsahuje dva stĺpce: prvý stĺpec sú x-ové (časové) hodnoty, druhý stĺpec sú zodpovedajúce namerané intenzity. Druhý typ súboru tvorí postupnosť takýchto cyklov merania, zodpovedá to Intenzitnému grafu. Obsahuje rovnaký prvý stĺpec:  x-ovú, časovú hodnotu a nasleduje viacero stĺpcov, so zodpovedajúcimi intenzitami v jednotlivých cykloch meraní. Údaje v CSV súboroch sa ukladajú vždy v netransformovanej podobe (pozri mobilita). Prvý riadok v každom type ukladaného CSV súboru obsahuje komentár, v ktorom sú všetky základné nastavenia, s ktorými graf vznikol (mobilita nie)."

Pošlite mi, prosím, ešte aktualizovanú verziu predtým ako to dáme zadávateľom. Ďakujem!

**Comment by krivanek06** [comment]
Zdravim, nahrali sme ďalšiu verziu : 
https://github.com/TIS2019-FMFI/ims-spectrometer/blob/master/Documents/Katalog_po%C5%BEiadaviek.pdf

veci, ktoré boli opravené v PDF-ku sú znázornené červenou farbou pre rýchle orientovanie.
Ak je dokument OK , tak samozrejme to prefarbíme späť na čierno a až potom pošleme zadavateľovi.

Väčšinu vecí sme zakomponovali do katalógu, s čím ale nesúhlasíme je : 

3.1.16. - 3.1.17. každý intenzitný na vlastné okno - chceme docieliť nech aplikácia je prehľadná. Ak si uživateľ dá vygenerovať 5 intenzitných grafov, musí narábať zo 6-timi oknami (5 intenzitných + hlavné).  Keď sme u zadavateĺa sledovali intenzitný graf, tiež to zrovna nebolo najväčšie. Je lepšie ak mu to aplikácia vypluje pod seba.

3.1.21 - "Zmena nastavení spôsobí zmazanie hlavného a hlavného intenzitného grafu". - Nespôsobí to.  Intenzitný graf sa maže len tlačidlom cancel (3.1.18.4). Zmena nastavený sa prejaví len na agregovaných dátach, ktoré sa zobrazia na ďaľšom vygenerom hlavnom grafe. Toto nie je v požiadavkách (v celku to tak vyplýva), ale môžem to tam hodiť k bodu  3.1.22 .

**Comment by pavelpetrovic** [comment]
ďakujem pekne za všetky úpravy.

napadajú mi ešte tieto otázky:

* ak bude viacero grafov naraz v okne a pouzivatelov monitor ma na vysku viac bodov, stale bude aplikacia na vysku zaberat iba 720 bodov?
   => mozno 3.2 upravit napr. takto?
    "Systém bude desktopová aplikácia. Bude použiteľná na počítači, ktorého displej má rozlíšenie aspoň 1280 × 720 bodov."

* keď bude zobrazených viacero intenzitných grafov, píšete, že každý má svoju RGB škálu. Toto zobrazenie (ak rozumiem) chcú používať hlavne na porovnávanie grafov. V tom prípade by sa im (aspoň niekedy) hodila spoločná RGB škála. Mám dva alternatívne návrhy:
   1) mať možnosť naeditovanú RGB škálu uložiť do súboru a načítať zo súboru
alebo - asi stačí aj toto:
   2) pri každej RGB škále je tlačidlo "apply to all", ktoré nastaví rovnakú RGB škálu aj do všetkých ostatných práve zobrazených intenzitných grafov.

* v tejto súvislosti si ale myslím, že resetovať RGB škálu pri každom stlačení Štart môže byť pre používateľa nepraktické - niečo si tam ponastavoval a teší sa z toho, ale chce to premerať znovu a bác, celé nastavenie škály je v háji...?

* slabým miestom dokumentu je 3.1.14 - je to nová vec, ktorá v dokumente ešte "nedozrela", ale v tejto formulácii to nie je dostatočné, aby sa to dalo podľa toho naprogramovať. veľmi by potešilo, keby ste to ešte trochu rozvili, ako presne sa to bude nastavovať.

* ešte vysvetlenie k bodom, ktoré ste nezahrnuli:

* k 3.1.16: filozofia návrhu pre samostatné okná je, aby to bolo aj pre Vás jednoduchšie - graf je uzavretý v okne, netreba riešiť scrollovanie a zložité zobrazovanie viacerých pod sebou - z niektorého vidno na obrazovke iba časť, druhú nie, ale sa napriek tomu prekresluje a mám pocit, že ak v tom istom okne má byť aj hlavný graf, tak tam už naozaj miesto nie je - v tej aplikácii, čo nám ukazovali bol hlavný graf na celé okno a aj ten jeden intezitný bol veľký. neviem si predstaviť ako tam môže vôjsť viac grafov aj s hlavným grafom naraz. je to celkom na Vás, ale dajte šancu aj zadávateľom k tomu ešte niečo povedať - okrem toho, že im pošlete KP, tak niektoré otázky ešte zdôraznite, nech si to zvážia, či to tak chcú mať - napr. toto.

* k 3.1.21: úvaha bola taká, že zmena nastavení spôsobí zmenu vykreslovania hlavného grafu a intenzitný graf sa skladá z jednotlivých hlavných grafov - čiže potom časť intenzitného grafu bude vzniknutá s jednými nastaveniami a iná časť s inými nastaveniami. Keďže sa nastavenia pri ukladaní grafu zapisujú do prvého riadku exportovaného súboru, tak potom čo sa tam zapíše? Ak len aktuálne platné, tak to bude nepravdivý údaj, lebo časť grafu vznikla s inými nastaveniami. A aj to zobrazenie bude nepravdivé, lebo tam stále budú svietiť údaje, ktoré vznikli pri nejakých iných nastaveniach. preto mi pripadalo korektné zmazať pri zmene nastavení aj hlavný intenzitný graf, ale neviem, či to tak chceli aj zadávatelia, takže je to na Vás.

OK, tak teda, keď tieto veci ešte zvážite alebo zapracujete, tak potom už, prosím, odošlite KP zadávateľom a poproste ich, aby si dokument celý dôkladne preštudovali, lebo podľa tohto dokumentu systém budete vyvíjať a nech teda ešte pošlú svoje pripomienky alebo otázky, ktoré ešte podľa potreby zapracujete, aby ste si aj Vy aj oni boli istí, že tieto formulácie sú vyhovujúce.

ďakujem
p.

**Comment by krivanek06** [comment]
Finálna verzia katalógu nahraná do : https://github.com/TIS2019-FMFI/ims-spectrometer/blob/master/Documents/Katalog_po%C5%BEiadaviek.pdf

Zadavateľ katalóg videl a odsúhlasil.
Issue zatváram.
