### ISSUE TITLE
Návrh - Bod A -  podrobná špecifikácia vonkajších interfejsov

### ISSUE THREAD

**Issue by krivanek06** [TIS2019-FMFI/ims-spectrometer#21]
Zadanie: "A. podrobná špecifikácia vonkajších interfejsov - ak aplikácia komunikuje s inými aplikáciami, súbormi, zariadeniami - tieto musia byť jasne a podrobne definované"

Dobrý zdroj informácii je minuloročný projekt, kde tiež riešili arduino. Dole sú významné body z ich návrhu, ktoré môžeš implementovať do nášho:

- Oni mali Arduino UNO, mi máme ShieldBuddy TC275 , čiže naša špecifikácia aruina bude iná ako mali oni.

- čo oni mali bod 2.5, tak u nás vytvor tabuľku, ktorý bude mať názov "meranie iónovej mobility" , 
model:  ShieldBuddy TC275
interface:                                    ostáva
signal output:                           (mi máme 5V )
maximálny čas meranie:            20 milisekúnd
hustota nameraných bodov:     škála 1 - 40 (to je ten sampling)
iónové zrážanie :                        2-4-6-8-10-12 ( vždy nárast o 2 , min 2, max 12, to je ten  gate)

- to čo oni maju 2.2.1 (špecifikacia IP kamery) ,tak mi nebudeme zatial písať špecifikáciu spektrometra (lebo je to nejaky home made)

ak potrebuješ ďaľšie informácie či odo mna, alebo od zadávatela, tak mi napíš.
Ak to budeš mať hotové, nahraj vlastný docs do google drive a potom sa to spojí s finálnou verzou.

projekt: https://github.com/TIS2018-FMFI/urychlovac/blob/Dokumenty/Navrh_rozpracovany_v2.pdf

ShieldBuddy TC275 : https://docs-emea.rs-online.com/webdocs/159d/0900766b8159d23a.pdf

**Comment by pavelpetrovic** [comment]
otazocka: aka je motivacia za tym, ze sa Arduino vymenilo za Shield Buddy TC275, pls?

**Comment by krivanek06** [comment]
Motiváciu nepoznám, používajú ten typ arduina.

Keďže arduino je open hardware, každá firma si vytvorila optimalizovaný pre vlastné účely. Náš typ arduina je výhodný v tom, že obsahuje 3 jadrá, takže paralelne vie vykonávať rozličné 3 úlohy.

Nám budú stačiť 2 jadrá ( core1 a core2, keďže sú o 25% rýchlejšie ako core0 ). 
core 1 bude čítať údaje zo spektrometra a core 2 bude posielať našu aplikáciu.

popis arduina: https://www.rs-online.com/designspark/bringing-multicore-to-the-arduino-world-with-shieldbuddy-tc275

**Comment by pavelpetrovic** [comment]
dakujem. este, raz, aby som to dobre pochopil: tento typ HW vybrali zadavatelia. ano?

**Comment by krivanek06** [comment]
Ano, zadávateľ ho vybral.

**Comment by pavelpetrovic** [comment]
prosim uviest, ze ext. rozhranie je spektrometer, ale implementacia komunikacie s nim, nie je sucastou projektu, kedze vyuzivate existujuci kod, ktory tuto  komunikaciu uz vyriesil.
