### ISSUE TITLE
Návrh - Bod D - podrobná špecifikácia a diagramy

### ISSUE THREAD

**Issue by krivanek06** [TIS2019-FMFI/ims-spectrometer#24]
Zadanie: "D. Zrozumiteľný a jednoznačný návrh implementácie, podľa ktorého sa dá aplikácia vyvinúť a ktorý bude obsahovať: UML component diagram, UML class diagram, a aspoň jeden z dvojice UML state a UML sequence diagram, zrozumiteľne vysvetlenú architektúru, rozdelenie na časti (moduly) a ich interfejsy, využité technológie, cieľové prostredie nasadenia do prevádzky."

Ak to budeš mať hotové, nahraj vlastný docs do google drive a potom sa to spojí s finálnou verzou.

minuloročný projekt : 
https://github.com/TIS2018-FMFI/urychlovac/blob/Dokumenty/Navrh_rozpracovany_v2.pdf

**Comment by krivanek06** [comment]
diagramy sú hodené sem : 
https://github.com/TIS2019-FMFI/ims-spectrometer/tree/small_fixes/Documents

**Comment by pavelpetrovic** [comment]
filozofia stavoveho diagramu:

(s * su akcie - stavove prechody)

vypnute
  
* zapnut

zapnute, caka na pripojenie PC

* PC vytvori pripojenie

PC pripojene, caka na prijatie nastaveni
 
* PC posle nastavenia

nastavene, pripravene na meranie  <------

* zaciatok merania

meria
                                        | 
* koniec merania  ------------------------

akcia vypnut z kazdeho do stavu vypnute
