### ISSUE TITLE
Arduino architecture redesign

### ISSUE THREAD

**Issue by krivanek06** [TIS2019-FMFI/ims-spectrometer#34]
predizajnovanie architektúry arduina zo single core na double core.
Aby jeden core čítal údaje zo spektrometra a druhý posielal na aplikáciu

**Comment by pavelpetrovic** [comment]
nepoznam tuto hw platformu, ale niekedy sa to riesi cez prerusenia - prijimanie znakov zo serioveho portu aktivuje prerusenie, ktore ich uklada do buffra a hlavne vlakno len kontroluje stav bufra a spracovava ho (v tomto pripade posiela do aplikacie).  (len taky bocny komentar k tomuto odo mna)
