### ISSUE TITLE
Návrh celok 

### ISSUE THREAD

**Issue by krivanek06** [TIS2019-FMFI/ims-spectrometer#52]
Tu budú popísané problémy, čo treba zmeniť na návrhu pred tým ako to pošleme:

- V úvode treba doplniť body : 1.1 , 1.2, 1.3 

- Bod 2.2.1 buď viac opísať shield buddy zo špecky (https://docs.rs-online.com/7e66/0900766b8159d23a.pdf) , alebo kompletne odstrániť. Je tam toho málo.

- Bod 2.3 Ionove zrážanie je 1- 20 (increment po 1)

- Bod 3.1.1 
-- Obsahuje údaje za čas definovaný uživateľom (môže to byť 0.5 sek aj 5sek)
-- "Súbor s intenzitnými údajmi - obsahuje graf s agregovanými údajmi " - zmeniť na "Obsahuje angregované údaje viacerých meraní"
-- "Súbor s mobilitnými údajmi – obsahuje údaje, na ktoré bol aplikovaný vzorec mobility" - toto zmazať
-- "Súbor s nastaveniami merania – obsahuje dané nastavenia daného merania" - zmeniť na "obsahuje nastavenia aplikácie a mobilitu".

- 3.1.2 - Doplniť len "záznam pre intenzitný graf bude obsahovať viacero stĺpcov, kde každý riadok bude signál v danom bode".

- Diagram komponentov - zmenil som foto, treba nahrať nové do dokumentu

- 4.4 - zmeniť obrázky grafu (main a heat) na iné (stačí aj s testovacími údajmi)

- Dorobiť class diagram (pridať aj niektoré hlavné metódy z frontendu)

**Comment by krivanek06** [comment]
zmeny:
- 2.3 
-- Hustota nameraných bodov - zmeniť "škála" na "mikrosekundy"
-- Iónové zrážanie - pridať slovo "gate", do lavej časti tabuľky, pridať slovo "mikrosekundy"

- 3.1.1
-- Súbor s agregovanými údajmi - odstrániť čas v zátvorkách
-- Súbor s intenzitnými údajmi - "obsahuje viaceré agregované údaje"

- 3.1.2
-- časté vyskytovanie slova "jednotlivých"
-- "Dáta jednotlivých senzorov sa budú ukladať do jednotlivých CSV súborov." prepísať na "Údaje zobrazené buď na intenzitnom grafe, alebo na hlavnom grafe sa budú ukladať do CSV súborov"
-- "Budú obsahovať dva stĺpce." prepísať na "Budú obsahovať minimálne dva stĺpce pri agregovaných údajov, kde prvý stĺpec je čas v mikrosekundách a druhý hodnota v bodoch. Pre intenzitný graf budeme mať počet stĺpcov zodpovedajúcich počtom agregovaných údajov v nich".

- 4.2 
-- prepísať "Sekcia Basic settings" na "Nastavenia aplikácie"
-- Ešte na koniec pridať " a hustota merania"

- 4.3 
-- prepísať "Sekcia Mobility" na "Nastavenie Mobility"

- 5.1.1 - zmenil som class diagram, daj tam nový z drivru.

--Skús aj parafrázovať vety ktore som napísal a ktoré sú v docs, nech sa neopakujú slová,
--Niekde sa ešte vyskytuje slovo "dáta" aj "údaje". Nahrať to len jedným z nich (viem, aj ja som písal jedno aj druhé) , ale použime len jedno slovo.

------------------------------------------------------------------
- Andrej 
-- Treba zmeniť obrázky v "4.4 sekcia grafu". Šupnite tam nejaké obrázky z netu (jeden z vás) na agregoavaný a intenzitný graf. Nemusí sa to na 100% zhrodvať s tým grafom, ktorý budeme vykreslovať v appke, len nech tam niečo je.


Ak toto všetko je, tak to submitneme

**Comment by krivanek06** [comment]
Okej, spravili sme teda návrh verziu 1 , diki chlapci za spoluprácu. 
Prihadzujem link : https://github.com/TIS2019-FMFI/ims-spectrometer/blob/master/application/Documents/TIS%20-%20n%C3%A1vrh.pdf 

teraz čakáme na review.

**Comment by pavelpetrovic** [comment]
moje poznamky z dnesneho stretnutia:

Juraj a Eduard nepritomni
--
za posledne dva tyzdne chybaju zapisnice
chybaju aj dve starsie zapisnice
zapisnice sa pisu vzdy priamo na stretnuti a na konci stretnutia sa stlaci [SAVE]. potom nemozeme byt v stave ako sme teraz.

nevieme, ci sa shieldbuddy bude menit kod, alebo nie
chyba mi v navrhu komunikacny protokol medzi shield buddy a PC aplikaciou a pripadne aj rozhranie Shild Buddy s pristrojom, ak sa v nom meni kod (alebo medzi novym a starym kodom...)
sekcia kom. protokoly obsahuje zbytocne encyklopedicke informacie, ale neobsahuje konkretnu strukturu a obsah kom. protokolu
rovnako formaty suborov su rozpisane podrobne ale v sekcii CSV format, prosim adresne prehodit pod jednotlive polozky v 3.1.1
ale chyba nam popis formatu suboru s nastaveniami
potrebujem vediet, ci sa tim stretol so zadavatelom s navrhom UI a podrobne presli celu funkcionalitu na obrazkoch
na zaciatku navrhu UI sa prosim odkazat na obrazok UI v KP (ak stale plati v takej verzii)
prosim doplnit aspon kratky vysvetlujuci text ku kazdemu diagramu (2 odstavce?)
prosim vytvorit novy stavovy diagram pre konkretnu entitu a jej pasivne stavy, medzi ktorymi sa prechadza stavovymi prechodmi trigerovanymi akciou, udalostou alebo casovym intervalom
navrh po schvaleni netreba menit, ale vo vyslednej technickej dokumentacii je potrebne aby to sedelo s vyslednou implementaciou, napr. si vytvorte jeden issue, v ktorom si zaznacite vsetky nove zmeny oproti navrhu pocas implementacie
testovacie scenare ako dokument prosim vypracovat, testy v kode su dolezite a chvalim
velmi dolezite: treba rovnomerne rozdelit pracu na implementacii, aj za cenu neoptimalneho vysledku. dolezitejsie je aby sa kazdy rovnomerne zapojil ako ze vysledok bude dokonaly.

napiste mailom, ked bude nova verzia navrhu a tiez testovacie scenare. v tyzdni od 9.12. skuste co najviac dokoncit implementaciu a v poslednom tyzdni sa urcite stretnime (ak nemozete v piatok tak v inom case)

**Comment by krivanek06** [comment]
Návrh sa zmenil podľa požiadaviek, 
link : https://github.com/TIS2019-FMFI/ims-spectrometer/blob/master/application/Documents/TIS%20-%20n%C3%A1vrh.pdf

**Comment by krivanek06** [comment]
Navrh je teda ok , zrkadlovy graf po dohode s pánom Matejčíkom nebude.

**Comment by pavelpetrovic** [comment]
A kto je na vine, ze zrkadlovy graf nebude?

**Comment by krivanek06** [comment]
Z intenzitného grafu na základe zafarbernie bodov sa dá vyčítať krivka grafu z ktorého vznikla., preto zrkadlový graf je nepotrebný. Radšej sme intenzitný graf natiahli na celú dĺžku obrazovky kvôli prehľadnosti.
O povolení vykovaní týchto zmien mám emailové potvrdenie od pána Matejčíka.

**Comment by pavelpetrovic** [comment]
viem si predstavit, ze ste prof. Matejcika ukecali, ale mne sa nepaci takyto ustup.
z farieb sice nieco vidno, ale je predsa ine, ak to vidim v priebehu na x-y grafe, nie?
ved preto to tam povodne malo byt. suhlasim s tym, ze ak tam je toho privela naraz,
tak to moze byt neprehladne, ale znamena to, ze spatne uz nie je mozne taky graf
zrekonstruovat? nie je to skoda?
