### ISSUE TITLE
Testovaci scenar

### ISSUE THREAD

**Issue by krivanek06** [TIS2019-FMFI/ims-spectrometer#63]
Zdravím,

Poprosím o vyjadrenie testovacieho scenáru.

link : https://github.com/TIS2019-FMFI/ims-spectrometer/blob/master/application/Documents/TIS_testovacie_scenare.pdf

**Comment by pavelpetrovic** [comment]
dakujem za dokument.
* slusna aplikacia by nemala padat s vynimkou, ale vynimky vzdy odchytavat a vypisat nejaku vlastnu chybovu spravu a pokial to nie je nevyhnutne, aplikaciu by to nemalo zhodit, ale vratit do nejakeho predchadzajuceho stavu
* testovacie scenare by mali byt jasne. nerozumiem ako nasleduje bod 1c za bodom 1b. bud sa to podarilo, alebo nepodarilo, ale asi nie oboje naraz?
* cize ak mam testovacie scenare chapat inak ako postupnost krokov, ktore mam na otestovanie vykonat, tak to treba niekde v tom dokumente vysvetlit - tyka sa to aj ostatnych bodov
* inak sa tesim a chvalim

**Comment by krivanek06** [comment]
Dopísal som omáčky k testovaciemu scenáru čo vlastne reprezentujú body a,b,c... a ako aplikácia reaguje na vyhadzovanie výnimiek. Zvyšok som potom už moc nemenil, len začiatok je iný
link : https://github.com/TIS2019-FMFI/ims-spectrometer/blob/master/application/Documents/TIS_testovacie_scenare.pdf

**Comment by pavelpetrovic** [comment]
dakujem, dokladnejsie ste sa s tym pohrali. tak teraz uz len ten navrh popri implementacii
