### ISSUE TITLE
Final changes

### ISSUE THREAD

**Issue by krivanek06** [TIS2019-FMFI/ims-spectrometer#67]
- Vlado
1. Mobilita
Ak sa klikne na checkbox pri mobilite treba pretransformovat X-ovu os.
Je to len staticky vzorec ktory ti zmeni hodnoty na X-ovej asy

- Andrej
4. Zapisnice
Chybaju nejake zapisnice, tak co si pišeme na whats upe, alebo issue v github tam davaj.

5. Finalny dokument
Po schvaleni navrhu treba spojit všetky dokumenty do jedneho 

6. Manual použivania
Ked dokoncime projekt bude treba spravit cca 1-2 strany v docs, napisat
ako sa to použiva
kedy co sa stane
ako sa to inštaluje (ak treba, ale toto asi nie ,lebo build ti vyhodi exe)

- Eduard
1. Nasadenie zakaznikovi 
Po dokonceni projektu nasadit zakaznikovi

**Comment by pavelpetrovic** [comment]
- double buffering +5bodov
- x,y priebezne zobrazovat 3.1.9 +4body
- doladit 3.1.10 - min.vyskusat
- 3.1.11 implementovat - 8 bodov
- 3.1.15 co najvohodnejsim sposobom podla moznosti +10bodov
- v githube kod finalny nie testovaci, odporucam test. prepinac
- citanie v sam. vlakne neprerus. gui
- 3.1.20.1 +7 bodov

**Comment by krivanek06** [comment]
Dobrý deň, z nasledovných úloh bolo spravené : 
- double buffering - ide
- x,y priebezne zobrazovat - ide
- mobilita (  3.1.10 ) - nejde 
- zoom ( 3.1.11 ) - ide
- custom RGB  ( 3.1.15 ) - ide ( v návode majú ako to spraviť)
-  3.1.20.1 (max dat v intenzitnom) - ide

Aplikácia s pridanými zmenami bola dodaná klientovi v stredu (12.02.2020). Zatiaľ sťažnosti neboli.

Zároveň sme spojili aj finálny dokument dokopy : https://github.com/TIS2019-FMFI/ims-spectrometer/blob/master/Vysledny_dokument.pdf

Prácu robili kolegovia (Vlado, Andrej).

**Comment by AndrejKo2** [comment]
3.1.20.1 nie je implementovane v projekte

**Comment by pavelpetrovic** [comment]
chyba informacia o tom, ci ste dotiahli tento bod:
* citanie v sam. vlakne neprerus. gui
to je nutna podmienka uspesneho hodnotenia.

**Comment by pavelpetrovic** [comment]
ak ste toto neupravili, tak v tom pripade (vzhladom na to, ze bez toho ten softver prakticky nie je pouzitelny) navrhujem vzhladom na pokrocily datum vsetkym znamku E.

dajte vediet, ci suhlasite, alebo, ci to je zapracovane, prosim.

**Comment by krivanek06** [comment]
- čítanie v samostatnom vlákne nie je, máme async / await.
podľa microsoft docs by som vystilhol len tieto dva odseky:
https://docs.microsoft.com/sk-sk/previous-versions/visualstudio/visual-studio-2012/hh191443(v=vs.110)?redirectedfrom=MSDN

Async Improves Responsiveness 
"Asynchrony proves especially valuable for applications that access the UI thread because all UI-related activity usually shares one thread"

Threads
"The async-based approach to asynchronous programming is preferable to existing approaches in almost every case. In particular, **this approach is better than BackgroundWorker for IO-bound operations** because the code is simpler and you don't have to guard against race conditions. In combination with Task.Run, async programming is better than BackgroundWorker for CPU-bound operations because async programming separates the coordination details of running your code from the work that Task.Run transfers to the threadpool."

-----------------------------------------------------------------------------------
- SW keď sme prezentovali (aj vám), tak to meralo dáta z arduina a vykreslovalo to graf, čiže použiteľné to z časti je, ale ak sme zadávateľa neuspokojili to mi je ľúto. Výsledná známka, ak dobre viem, by mala byť kombináciou funkčného programu, spolupráci tímu a iných faktorov (písomky, atď). Niekedy projekty sú mimo kapacity vedomosti študentov a výsledok môže byť žiaľ takýto.

Známku dajte podľa vlastného zváženia.

Ďakujem.
-- Eduard

**Comment by pavelpetrovic** [comment]
toto vsetko by platilo, ak by ste to pouzili spravne, avsak to nie je ten pripad, kedze podla Vasich vlastnych slov necitate dalsiu hodnotu, kym sa nestihne vykreslit. proces nacitavania musi byt nezavisly od procesu zobrazovania. akymi prostriedkami to dosiahnete, je pre mna nepodstatne. vyuzitim threadov je to jednoduche, priamociare a jasne. pri async zjavne ani diva svina netusi, aky vypoctovy model tam je a v konecnom dosledku sa deje to iste, len je to zapisane nepriamo. ja nevidim v tomto ziadne benefity pre tento typ aplikacie, ale nebranim sa ziadnej technologii, ak vysledok je funkcny. vo Vasom pripade vsak vysledok nie je funkcny, nacitavanie nemoze byt zavisle na zobrazovani v ziadnom pripade a ak to sposobuje, ze nacitavanie prestane fungovat, tak uz vobec nie.vysledny softver hodnotim ako nefunkcny, zadanie ako nesplnene a je hodne fx. z milosti vzhladom na odvedenu pracu Vam dam E, ale mam z toho zly pocit. zacalo to tym, ze uz prvu ulohu, ktora bola povinna, ste nesplnili a skoncilo to odovzdanim chybneho nepouzitelneho softveru, pricom uprava by si vyziadala asi hodinu roboty. sklamanie na vsetkych urovniach.
