### ISSUE TITLE
Arduin pripojenie

### ISSUE THREAD

**Issue by krivanek06** [TIS2019-FMFI/ims-spectrometer#7]
Backend: 
Vytvorenie triedy, ktorý bude zodpovedná za čítanie a zapisovanie údajov do arduina.
Bude mať atribúty pre nastavenie arduina: 
- Gate (štartujúci signál, ktorý spúšťa ióny do driftu v spektrometri) 
- Sampling (časová hodnota v mikrosekundách určujúca ako často čítam signál z AD prevodníka)
- Points (doba jedného merania)

Jedno meranie je fixných 20 000 milisekúnd
vzorece :  
Points = 20 000 / sampling
Drift = Gate * Sampling (ako dlho bude otvorená brána pre ióny)

**Comment by pavelpetrovic** [comment]
priklad na testovaci kod pre Arduino:

void setup() {
  Serial.begin(9600);
}

void loop() {

  Serial.print("@ ");
  for (int i = 0; i < 100; i++)
  {
    Serial.print(i);
    Serial.print(" ");
  }
    Serial.println();

  delay(20);
}

**Comment by krivanek06** [comment]
je to ok, mal som dáta, issue zatváram
